# -*- coding: utf-8 -*-
"""Project2DA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bf2_RWU-nvVBUDBBpFGb4RSEm6WDeOSW
"""

## IMPORT ##

"""# NOTES
# to do
## remove the unrated rows
## combine two csvs via anime id
##---------
# reasoning:
## rating column will be removed per instructions
## members column will be removed as it introduces a bias into the final model (more ratings = more users = more popular = good anime, and we do not know the ratings so it is almost "cheating")
"""